GET http://localhost:8080/home
################################################################

GET http://localhost:8080/cars

################################################################

GET https://riderendezvous.onrender.com/home